version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bugtracker_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bugtracker
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: bugtracker_web
    depends_on:
      - db
    ports:
      - '8000:8000'
    env_file:
      - .env.docker        # Load Docker-specific environment variables
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  db_data:
